force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated by HR</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vacancy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Recruiter who accepted this vacancy and is responsible for search (Only Recruiter role can be assigned)</description>
    <label>Responsible</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only Recruiter role can be assigned</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Recruiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Vacancy status, &quot;New&quot; and &quot;In-Process&quot; are set by the system. &quot;Cancelled&quot; and &quot;Closed&quot; are available only when the vacancy is already saved and can be edited only by the Manager who opened the vacancy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/VacancyCandidateAssociation__c.object-meta.xml
<CustomObject>
    <label>Candidate to Vacancy</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>VacancyCandidateAssociation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates to Vacancy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR 2</booleanFilter>
        <errorMessage>Please associate only candidates that are under your ownership and are Validated by HR.</errorMessage>
        <filterItems>
            <field>Candidate__c.OwnerId</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Assign Vacancy</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Vacancy__c.field-meta.xml
<CustomField>
    <fullName>Vacancy__c</fullName>
    <label>Vacancy</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Vacancy is not In-Process or you are not responsible for this vacancy.</errorMessage>
        <filterItems>
            <field>Vacancy__c.Status__c</field>
            <operation>equals</operation>
            <value>In-Process</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Vacancy__c.Responsible__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Assign Candidate</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/TestMyVacanciesExt.cls
@IsTest
public class TestMyVacanciesExt{

    @TestSetup static void setup() {
        // Create common user accounts 
        Profile mp = [SELECT Id FROM Profile WHERE Name='Manager'];
        System.debug('Manager Profile: ' + mp.Id);
        User manager = new User(Alias = 'muser', Email='muser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles', Username='muser@testorg.com');
        manager.ProfileId = mp.Id;
        insert manager;

        Profile rp = [SELECT Id FROM Profile WHERE Name='Recruiter'];
        System.debug('Recruiter Profile: ' + rp.Id);
        User recruiter = new User(Alias = 'ruser', Email='ruser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles', Username='ruser@testorg.com');
        recruiter.ProfileId = rp.Id;
        insert recruiter;

        System.runAs(recruiter) {
            Candidate__c candidate = new Candidate__c(Status__c = 'Validated By HR');
            insert candidate;
        }
    }

    private static testMethod void TestMyVacanciesExtNoVacancies(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Candidate__c candidate = [SELECT Status__c FROM Candidate__c WHERE OwnerId=:recruiter.Id LIMIT 1];

        System.runAs(recruiter) {
            // Act
            Test.startTest();

            PageReference pref = new PageReference('/'+candidate.Id);
            pref.getParameters().put('id', candidate.Id);
            Test.setCurrentPage(pref);
            
            ApexPages.StandardController stdCtr = new ApexPages.StandardController(candidate);
            MyVacanciesExt objMyVacanciesExt  = new MyVacanciesExt(stdCtr);

            Test.setCurrentPageReference(pref);  //vf page request
            objMyVacanciesExt.onload();

            // Assert 
            System.assertEquals(candidate.Id, objMyVacanciesExt.candidate.Id);
            System.assertEquals(0, objMyVacanciesExt.vacancies.size());

            objMyVacanciesExt.getSelected();
            objMyVacanciesExt.Apply();

            Test.stopTest();
        } 
    }

    private static testMethod void TestMyVacanciesExtHaveVacancyAssignedSelectAndApply(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Vacancy__c vacancy;
        System.runAs(manager) {
            vacancy = new Vacancy__c(Responsible__c=recruiter.Id);
            insert vacancy;
        }
        Candidate__c candidate = [SELECT Status__c FROM Candidate__c WHERE OwnerId=:recruiter.Id LIMIT 1];

        System.runAs(recruiter) {
            System.debug('Current User: ' + UserInfo.getUserName());
            System.debug('Current Profile: ' + UserInfo.getProfileId());

            // Act
            Test.startTest();

            PageReference pref = new PageReference('/'+candidate.Id);
            pref.getParameters().put('id', candidate.Id);
            Test.setCurrentPage(pref);
            
            ApexPages.StandardController stdCtr = new ApexPages.StandardController(candidate);
            MyVacanciesExt objMyVacanciesExt  = new MyVacanciesExt(stdCtr);

            Test.setCurrentPageReference(pref);  //vf page request
            objMyVacanciesExt.onload();

            objMyVacanciesExt.vacancies[0].selected = true;
            objMyVacanciesExt.getSelected();
            objMyVacanciesExt.Apply();

            Test.stopTest();

            // Assert 
            System.assertEquals(candidate.Id, objMyVacanciesExt.candidate.Id);
            System.assertEquals(1, objMyVacanciesExt.vacancies.size());

            VacancyCandidateAssociation__c[] SelectedVacancies = [SELECT Id FROM VacancyCandidateAssociation__c WHERE Candidate__c = :candidate.Id AND Vacancy__c = :vacancy.Id];
            System.assertEquals(1, SelectedVacancies.size());
        } 
    }

    private static testMethod void TestMyVacanciesExtAddValidatedCandidateDeselectThenApply(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Vacancy__c vacancy;
        System.runAs(manager) {
            vacancy = new Vacancy__c(Responsible__c=recruiter.Id);
            insert vacancy;
        }
        Candidate__c candidate = [SELECT Status__c FROM Candidate__c WHERE OwnerId=:recruiter.Id LIMIT 1];

        System.runAs(recruiter) {
            System.debug('Current User: ' + UserInfo.getUserName());
            System.debug('Current Profile: ' + UserInfo.getProfileId());

            VacancyCandidateAssociation__c vca = new VacancyCandidateAssociation__c(Vacancy__c=vacancy.Id, Candidate__c=candidate.Id);
            insert vca;

            // Act
            Test.startTest();

            PageReference pref = new PageReference('/'+candidate.Id);
            pref.getParameters().put('id', candidate.Id);
            Test.setCurrentPage(pref);
            
            ApexPages.StandardController stdCtr = new ApexPages.StandardController(candidate);
            MyVacanciesExt objMyVacanciesExt  = new MyVacanciesExt(stdCtr);

            Test.setCurrentPageReference(pref);  //vf page request
            objMyVacanciesExt.onload();

            // Assert
            System.assertEquals(candidate.Id, objMyVacanciesExt.candidate.Id);
            System.assertEquals(1, objMyVacanciesExt.vacancies.size());

            // Act
            objMyVacanciesExt.vacancies[0].selected = false;
            objMyVacanciesExt.getSelected();
            objMyVacanciesExt.Apply();

            // Assert
            VacancyCandidateAssociation__c[] SelectedVacancies = [SELECT Id FROM VacancyCandidateAssociation__c WHERE Candidate__c = :candidate.Id AND Vacancy__c = :vacancy.id];
            System.assertEquals(0, SelectedVacancies.size());
            Test.stopTest();
        } 
    }

    private static testMethod void TestMyVacanciesExtNewCandidateIsNotListed(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        List<Vacancy__c> vacancies = new List<Vacancy__c>();
        System.runAs(manager) {
            vacancies.add(new Vacancy__c());
            vacancies.add(new Vacancy__c(Responsible__c=recruiter.Id, Status__c='Closed'));
            vacancies.add(new Vacancy__c(Responsible__c=recruiter.Id, Status__c='Cancelled'));
            insert vacancies;
        }
        Candidate__c candidate = [SELECT Status__c FROM Candidate__c WHERE OwnerId=:recruiter.Id LIMIT 1];

        System.runAs(recruiter) {
            // Act
            Test.startTest();

            PageReference pref = new PageReference('/'+candidate.Id);
            pref.getParameters().put('id', candidate.Id);
            Test.setCurrentPage(pref);
            
            ApexPages.StandardController stdCtr = new ApexPages.StandardController(candidate);
            MyVacanciesExt objMyVacanciesExt  = new MyVacanciesExt(stdCtr);

            Test.setCurrentPageReference(pref);  //vf page request
            objMyVacanciesExt.onload();

            // Assert 
            System.assertEquals(candidate.Id, objMyVacanciesExt.candidate.Id);
            System.assertEquals(0, objMyVacanciesExt.vacancies.size());

            objMyVacanciesExt.getSelected();
            objMyVacanciesExt.Apply();

            Test.stopTest();
        } 
    }
}