force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated by HR</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vacancy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/DaysLeftToClose__c.field-meta.xml
<CustomField>
    <fullName>DaysLeftToClose__c</fullName>
    <description>Indicates how many days is left to StartDate</description>
    <formula>FLOOR(DATETIMEVALUE(StartDate__c) - NOW())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DaysLeftToClose</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Vacancy brief description</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Required technical level</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>d0</fullName>
            </value>
            <value>
                <fullName>d1</fullName>
            </value>
            <value>
                <fullName>d2</fullName>
            </value>
            <value>
                <fullName>d3</fullName>
            </value>
            <value>
                <fullName>d4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Recruiter who accepted this vacancy and is responsible for search (Only Recruiter role can be assigned)</description>
    <label>Responsible</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only Recruiter role can be assigned</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Recruiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Vacancy status, &quot;New&quot; and &quot;In-Process&quot; are set by the system. &quot;Cancelled&quot; and &quot;Closed&quot; are available only when the vacancy is already saved and can be edited only by the Manager who opened the vacancy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the vacancy</description>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/VacancyCandidateAssociation__c.object-meta.xml
<CustomObject>
    <label>Candidate to Vacancy</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>VacancyCandidateAssociation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates to Vacancy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR 2</booleanFilter>
        <errorMessage>Please associate only candidates that are under your ownership and are Validated by HR.</errorMessage>
        <filterItems>
            <field>Candidate__c.OwnerId</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Assign Vacancy</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Vacancy__c.field-meta.xml
<CustomField>
    <fullName>Vacancy__c</fullName>
    <label>Vacancy</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Vacancy is not In-Process or you are not responsible for this vacancy.</errorMessage>
        <filterItems>
            <field>Vacancy__c.Status__c</field>
            <operation>equals</operation>
            <value>In-Process</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Vacancy__c.Responsible__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Assign Candidate</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/MyVacanciesExt.cls
public class MyVacanciesExt {

    private List<VacancyCandidateAssociation__c> SelectedVacancies = new List<VacancyCandidateAssociation__c>();
    private Map<Id,VacancyCandidateAssociation__c> selectedVacanciesMap = new Map<Id,VacancyCandidateAssociation__c>();
    
    public List<VacancyWrapper> vacancies { get; private set; } {vacancies = new List<VacancyWrapper>();}
    public Candidate__c candidate { get; private set; }

    public MyVacanciesExt(ApexPages.StandardController controller) {
        candidate = [SELECT Status__c FROM Candidate__c WHERE Id = :controller.getId()];
    }

    public PageReference getSelected() {
        SelectedVacancies.clear();

        for(VacancyWrapper wrapper: vacancies) {
            if (wrapper.selected == true) {
                SelectedVacancies.add(new VacancyCandidateAssociation__c(Candidate__c = candidate.Id,Vacancy__c = wrapper.vacancy.Id));
            }
        }

        return null;
    }

    public PageReference onload() {
        VacancyWrapper vw;

        if (candidate.Status__c == 'Validated By HR') {
            SelectedVacancies = [SELECT Vacancy__c, Candidate__c FROM VacancyCandidateAssociation__c WHERE Candidate__c = :candidate.Id];
            for (VacancyCandidateAssociation__c vcAssociation : SelectedVacancies) {
                selectedVacanciesMap.put(vcAssociation.Vacancy__c, vcAssociation);
            }

            for (Vacancy__c v: [SELECT Id, Owner.Name, Name, Title__c, Level__c, Description__c, DaysLeftToClose__c 
                                FROM Vacancy__c 
                                WHERE Status__c = 'In-Process' and Responsible__c = :userInfo.getUserId()]) {
                vw = new VacancyWrapper(v);
                vw.selected = selectedVacanciesMap.containsKey(v.Id);
                vacancies.add(vw);
            }
        }

        return null;
    }

    public PageReference Apply() {
        this.ApplySelected();

        PageReference candidatePage = new ApexPages.StandardController(candidate).view();
        candidatePage.setRedirect(true);

        return candidatePage;
    }

    private void ApplySelected() {
        List<VacancyCandidateAssociation__c> oldCandidateVacancies = [SELECT Id
            FROM VacancyCandidateAssociation__c 
            WHERE Candidate__c=:candidate.Id ];

        if (oldCandidateVacancies.size() > 0) {
            delete oldCandidateVacancies;
        }
            
        insert SelectedVacancies;
    }

    public class VacancyWrapper
    {
        public Vacancy__c vacancy {get; set;}
        public Boolean selected {get; set;}
        public VacancyWrapper(Vacancy__c v) {
            vacancy = v;
            selected = false;
        }
    }
}