force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Candidate&#39;s First Name</description>
    <label>FirstName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Candidate&#39;s Last Name</description>
    <label>LastName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated by HR</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Vacancies__c.field-meta.xml
<CustomField>
    <fullName>Vacancies__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lists all open vacancies 
where the candidate is proposed</description>
    <label>Vacancies</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Vacancy__c.Status__c</field>
            <operation>contains</operation>
            <value>In-Process</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vacancy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Vacancy brief description</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Required technical level</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>d0</fullName>
            </value>
            <value>
                <fullName>d1</fullName>
            </value>
            <value>
                <fullName>d2</fullName>
            </value>
            <value>
                <fullName>d3</fullName>
            </value>
            <value>
                <fullName>d4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Recruiter who accepted this vacancy and is responsible for search (Only Recruiter role can be assigned)</description>
    <label>Responsible</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only Recruiter role can be assigned</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Recruiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Vacancy planned start date</description>
    <label>StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Vacancy status, &quot;New&quot; and &quot;In-Process&quot; are set by the system. &quot;Cancelled&quot; and &quot;Closed&quot; are available only when the vacancy is already saved and can be edited only by the Manager who opened the vacancy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the vacancy</description>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/VacancyCandidateAssociation__c.object-meta.xml
<CustomObject>
    <label>Candidate to Vacancy</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>VacancyCandidateAssociation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates to Vacancy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR 2</booleanFilter>
        <errorMessage>Please associate only candidates that are under your ownership and are Validated by HR.</errorMessage>
        <filterItems>
            <field>Candidate__c.OwnerId</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Assign Vacancy</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Vacancy__c.field-meta.xml
<CustomField>
    <fullName>Vacancy__c</fullName>
    <label>Vacancy</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Vacancy is not In-Process or you are not responsible for this vacancy.</errorMessage>
        <filterItems>
            <field>Vacancy__c.Status__c</field>
            <operation>equals</operation>
            <value>In-Process</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Vacancy__c.Responsible__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Assign Candidate</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/ManageVacanciesExt.cls
public with sharing class ManageVacanciesExt {
    private static final String MESSAGE_NO_VACANCIES = 'No matching Vacancies found.';

    private List<Vacancy__c> SelectedVacancies = new List<Vacancy__c>();
    private ApexPages.StandardSetController controller;
    public List<VacancyWrapper> vacList { get; private set; } {vacList = new List<VacancyWrapper>();}


    private List<String> filteredStatuses = new List<String>{
        RecruitmentConstants.VACANCY_STATUS_CANCELLED,
        RecruitmentConstants.VACANCY_STATUS_CLOSED
    };

    public class VacancyWrapper {
        public Vacancy__c Vacancy {get; set;}
        public Boolean selected {get; set;}
        public Id Candidate {get; set;}
        public VacancyWrapper(Vacancy__c v) {
            Vacancy = v;
            selected = false;
            Candidate = null;
        }
    }

    public ApexPages.StandardSetController vacancyRecords {
        get {
            if(vacancyRecords == null) {
                vacancyRecords = new ApexPages.StandardSetController(
                    Database.getQueryLocator([
                        SELECT Id, Status__c, Name, Title__c, Candidate__c, Description__c, Level__c, Responsible__c, StartDate__c,
                            (SELECT Name, Vacancy__c, Candidate__r.Status__c, Candidate__r.Name, Candidate__r.Vacancies__c, Candidate__r.LastName__c, Candidate__r.FirstName__c, Candidate__r.Comments__c, Candidate__r.OwnerId FROM VacancyCandidateAssociations__r) 
                        FROM Vacancy__c
                        WHERE Status__c NOT IN :filteredStatuses ])
                );
            }
            return vacancyRecords;
        }
        private set;
    }

    public Map<Id, List<Candidate__c>> vacancyCandidateDetailsMap {
        get {
            if(vacancyCandidateDetailsMap == null) {
                vacancyCandidateDetailsMap = new Map<Id, List<Candidate__c>>();
                for (Id vacancyId : vacancyRecordsMap.keySet()) {
                    vacancyCandidateDetailsMap.put(vacancyId, candidateDetails(vacancyId));
                }
            }
            return vacancyCandidateDetailsMap;
        }
        private set;
    }

    public PageReference getSelected() {
        SelectedVacancies.clear();

        for(VacancyWrapper wrapper: vacList) {
            if (wrapper.Vacancy.Candidate__c != null) {
                wrapper.Candidate = wrapper.Vacancy.Candidate__c;
            }
            if (wrapper.selected == true) {
                SelectedVacancies.add(wrapper.Vacancy);
            }
        }

        return null;
    }

    public ManageVacanciesExt(ApexPages.StandardSetController setController) {
        controller = setController;
    }

    public PageReference onLoad() {
        VacancyWrapper vw;
        vacList.clear();
        
        if(vacancyRecords.getRecords().size() == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, MESSAGE_NO_VACANCIES));
        }

        for (Vacancy__c v: (List<Vacancy__c>)vacancyRecords.getRecords()) {
            vw = new VacancyWrapper(v);
            vw.selected = false;
            vacList.add(vw);
        }
        
        return null;
    }

    public PageReference closeVacancies() {
//        PageReference pageRef = new PageReference(ApexPages.currentPage().getUrl());
//        pageRef.setRedirect(true);

        doCloseVacancies(SelectedVacancies);

        vacancyRecords = null;
        onLoad();

        return null;
    }

    public PageReference cancelVacancies() {
//        PageReference pageRef = new PageReference(ApexPages.currentPage().getUrl());
//        pageRef.setRedirect(true);

        doCancelVacancies(SelectedVacancies);

        vacancyRecords = null;
        onLoad();

        return null;
    }

    private List<Candidate__c> candidateDetails(String vacancyId) {
        List<Candidate__c> candidateList = new List<Candidate__c>();
        List<VacancyCandidateAssociation__c> vacancyCandidateAssociations = vacancyRecordsMap.get(vacancyId).VacancyCandidateAssociations__r;
        
        for(VacancyCandidateAssociation__c vca : vacancyCandidateAssociations) {
            candidateList.add(vca.Candidate__r);
        }

        return candidateList;
    }

    private Map<Id, Vacancy__c> vacancyRecordsMap {
        get {
            if(vacancyRecordsMap == null) {
                vacancyRecordsMap = new Map<Id, Vacancy__c>();
                vacancyRecordsMap.putAll((List<Vacancy__c>)vacancyRecords.getRecords());
            }

            return vacancyRecordsMap;
        }
        private set;
    }

    private void doCloseVacancies(List<Vacancy__c> listVacancies) {
        Map<Id,VacancyCandidateAssociation__c> vacancyCandidateAssociations = new Map<Id,VacancyCandidateAssociation__c>();
        Map<Id,Candidate__c> candidatesToHireMap = new Map<Id,Candidate__c>();
        List<Candidate__c> candidateToHireList = new List<Candidate__c>();        
        List<Vacancy__c> closedVacancyList = new List<Vacancy__c>();
        List<Vacancy__c> cancelledVacancyList = new List<Vacancy__c>();
        
        VacancyTool.splitVacanciesToClosedAndCancelled(listVacancies, closedVacancyList, cancelledVacancyList);
        
        updateVacancyClosedStatusAddingMessages(closedVacancyList, candidatesToHireMap, vacancyCandidateAssociations);
        updateVacancyCancelledStatusAddingMessages(cancelledVacancyList, vacancyCandidateAssociations, true);
        
        getBackVacancyCandidateAssociations(candidatesToHireMap.keySet(), vacancyCandidateAssociations);
        CandidateTool.setCandidateHired(candidatesToHireMap.values(), candidateToHireList);
        
        update candidateToHireList;
        delete vacancyCandidateAssociations.values();
    }

    private void getBackVacancyCandidateAssociations(Set<Id> candidateIds, Map<Id,VacancyCandidateAssociation__c> vacancyCandidateAssociations) {
        vacancyCandidateAssociations.putAll([
            SELECT Id
            FROM VacancyCandidateAssociation__c
            WHERE Candidate__c IN :candidateIds
        ]);
    }

    private void updateVacancyClosedStatusAddingMessages(
        List<Vacancy__c> closedVacancyList,
        Map<Id,Candidate__c> candidatesToHireMap,
        Map<Id,VacancyCandidateAssociation__c> vacancyCandidateAssociations
    ) {
        Candidate__c Candidate;
        List<VacancyCandidateAssociation__c> tempVacancyCandidateAssociations = new List<VacancyCandidateAssociation__c>();
        List<Database.SaveResult> updateResults = Database.update(closedVacancyList, false);
        
        for(Integer i = 0; i < updateResults.size(); i++){
            if (!updateResults.get(i).isSuccess()){
                Database.Error error = updateResults.get(i).getErrors().get(0);
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, error.getMessage()));

                continue;
            }

            Vacancy__c Vacancy = closedVacancyList.get(i);
            tempVacancyCandidateAssociations = Vacancy.VacancyCandidateAssociations__r;
            vacancyCandidateAssociations.putAll(tempVacancyCandidateAssociations);

            for(VacancyCandidateAssociation__c vca : tempVacancyCandidateAssociations) {
                Candidate = vca.Candidate__r;
                if (Candidate.Id == Vacancy.Candidate__c) {
                    Candidate.Vacancies__c = Vacancy.Id;
                    candidatesToHireMap.put(Candidate.Id, Candidate);
                }    
            }

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Vacancy ' + Vacancy.Name + ' have been successfully closed.'));
        }
    }

    private void doCancelVacancies(List<Vacancy__c> listVacancies) {
        Map<Id,VacancyCandidateAssociation__c> vacancyCandidateAssociations = new Map<Id,VacancyCandidateAssociation__c>();
        List<Vacancy__c> cancelledVacancyList = new List<Vacancy__c>();

        VacancyTool.trySetVacancyCancelledStatus(listVacancies, cancelledVacancyList);
        updateVacancyCancelledStatusAddingMessages(cancelledVacancyList, vacancyCandidateAssociations, false);

        System.debug('doCancelVacancies delete vacancyCandidateAssociations' + vacancyCandidateAssociations.values());
        delete vacancyCandidateAssociations.values();
    }

    private void updateVacancyCancelledStatusAddingMessages(
        List<Vacancy__c> updateList,
        Map<Id,VacancyCandidateAssociation__c> vacancyCandidateAssociations,
        Boolean isCloseVacancyContext
    ) {
        List<Database.SaveResult> updateResults = Database.update(updateList, false);

        for(Integer i=0;i<updateResults.size();i++){
            if (!updateResults.get(i).isSuccess()){
                Database.Error error = updateResults.get(i).getErrors().get(0);
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, error.getMessage()));
                 
                continue;
            } 
            
            vacancyCandidateAssociations.putAll(vacancyRecordsMap.get(updateList.get(i).Id).VacancyCandidateAssociations__r);

            if (isCloseVacancyContext == true) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,'Vacancy ' + updateList.get(i).Name + ' has been cancelled since the vacancy has no candidates selected.'));

                return;
            }

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Vacancy ' + updateList.get(i).Name + ' has been successfully cancelled.'));
        }
    }
}