force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated by HR</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Vacancies__c.field-meta.xml
<CustomField>
    <fullName>Vacancies__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lists all open vacancies 
where the candidate is proposed</description>
    <label>Vacancies</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Vacancy__c.Status__c</field>
            <operation>contains</operation>
            <value>In-Process</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vacancy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Recruiter who accepted this vacancy and is responsible for search (Only Recruiter role can be assigned)</description>
    <label>Responsible</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only Recruiter role can be assigned</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Recruiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Vacancy status, &quot;New&quot; and &quot;In-Process&quot; are set by the system. &quot;Cancelled&quot; and &quot;Closed&quot; are available only when the vacancy is already saved and can be edited only by the Manager who opened the vacancy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/VacancyCandidateAssociation__c.object-meta.xml
<CustomObject>
    <label>Candidate to Vacancy</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>VacancyCandidateAssociation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates to Vacancy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR 2</booleanFilter>
        <errorMessage>Please associate only candidates that are under your ownership and are Validated by HR.</errorMessage>
        <filterItems>
            <field>Candidate__c.OwnerId</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Assign Vacancy</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Vacancy__c.field-meta.xml
<CustomField>
    <fullName>Vacancy__c</fullName>
    <label>Vacancy</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Vacancy is not In-Process or you are not responsible for this vacancy.</errorMessage>
        <filterItems>
            <field>Vacancy__c.Status__c</field>
            <operation>equals</operation>
            <value>In-Process</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Vacancy__c.Responsible__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Assign Candidate</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/TestVacancyApexSharing.cls
@IsTest
public class TestVacancyApexSharing{

    @TestSetup static void setup() {
        // Create common user accounts 
        Profile mp = [SELECT Id FROM Profile WHERE Name='Manager']; 
        User manager = new User(Alias = 'muser', Email='muser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles', Username='muser@testorg.com');
        manager.ProfileId = mp.Id;
        insert manager;

        Profile rp = [SELECT Id FROM Profile WHERE Name='Recruiter'];
        User recruiter = new User(Alias = 'ruser', Email='ruser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles', Username='ruser@testorg.com');
        recruiter.ProfileId = rp.Id;
        insert recruiter;
    }

    private static testMethod void TestVacancyApexSharingNoResponsibleSet(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Vacancy__c Vacancy;
        List<Vacancy__c> actualVacancy;

        System.runAs(manager) {
            Vacancy = new Vacancy__c();
            insert Vacancy;
        }
        
        System.runAs(recruiter) {
            // Act
            actualVacancy = [SELECT Id FROM Vacancy__c WHERE Id = :Vacancy.Id LIMIT 1];
            System.assertEquals(0, actualVacancy.size());
        } 
    }
    
    private static testMethod void TestVacancyApexSharingHasResponsibleSet(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Vacancy__c Vacancy;
        List<Vacancy__c> actualVacancy;

        System.runAs(manager) {
            Vacancy = new Vacancy__c(Responsible__c=recruiter.Id);
            insert Vacancy;
        }
        
        System.runAs(recruiter) {
            // Act
            actualVacancy = [SELECT Id FROM Vacancy__c WHERE Id = :Vacancy.Id LIMIT 1];
            System.assertEquals(1, actualVacancy.size());
        } 
    }
    
    private static testMethod void TestVacancyApexSharingHasResponsibleChanged(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Vacancy__c Vacancy;
        List<Vacancy__c> actualVacancy;

        System.runAs(manager) {
            Vacancy = new Vacancy__c(Responsible__c=recruiter.Id);
            insert Vacancy;
        }
        
        System.runAs(recruiter) {
            // Act
            actualVacancy = [SELECT Id FROM Vacancy__c WHERE Id = :Vacancy.Id LIMIT 1];
            System.assertEquals(1, actualVacancy.size());
        }
        
        System.runAs(manager) {
            Vacancy.Responsible__c=null;
            update Vacancy;
        }
        
        System.runAs(recruiter) {
            // Act
            actualVacancy = [SELECT Id FROM Vacancy__c WHERE Id = :Vacancy.Id LIMIT 1];
            System.assertEquals(0, actualVacancy.size());
        }
    }
    
    private static testMethod void TestVacancyApexSharingHasResponsibleAndGetClosed(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Vacancy__c Vacancy;
        Candidate__c Candidate;
        VacancyCandidateAssociation__c vacancyCandidateAssociation;
        List<Candidate__c> actualCandidate;

        System.runAs(manager) {
            Vacancy = new Vacancy__c(Responsible__c=recruiter.Id);
            insert Vacancy;
        }
        
        System.runAs(recruiter) {
            // Act            
            Candidate = new Candidate__c(Status__c='Validated By HR');
            insert Candidate;
        }

        System.runAs(recruiter) {
            vacancyCandidateAssociation = new VacancyCandidateAssociation__c(Candidate__c= Candidate.Id, Vacancy__c= Vacancy.Id);
            insert vacancyCandidateAssociation;
        }
        
        System.runAs(manager) {
            // Act
            actualCandidate = [SELECT Id FROM Candidate__c WHERE Id = :Candidate.Id LIMIT 1];
            System.assertEquals(1, actualCandidate.size());
            
            Test.startTest();
            Candidate.Status__c = 'Hired';
            Candidate.Vacancies__c = Vacancy.Id;
            update Candidate;
            
            Vacancy.Status__c='Closed';
            Vacancy.Candidate__c= Candidate.Id;
            update Vacancy;
            
            delete vacancyCandidateAssociation;
            Test.stopTest();
            
            // Act
            actualCandidate = [SELECT Id FROM Candidate__c WHERE Id = :Candidate.Id LIMIT 1];
            System.assertEquals(1, actualCandidate.size());
        }
    }
}