force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated by HR</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vacancy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Vacancy status, &quot;New&quot; and &quot;In-Process&quot; are set by the system. &quot;Cancelled&quot; and &quot;Closed&quot; are available only when the vacancy is already saved and can be edited only by the Manager who opened the vacancy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VacancyTool.cls
public class VacancyTool {
    public static void splitVacanciesToClosedCancelled (
        List<Vacancy__c> sourceVacancyList,
        List<Vacancy__c> closedVacancyList,
        List<Vacancy__c> cancelledVacancyList
    ) {
        for (Vacancy__c vacancy : sourceVacancyList) {
            if (!isOpened(vacancy)) {
                continue;
            }

            if (canBeClosed(vacancy)) {
                vacancy.Status__c = RecruitmentConstants.VACANCY_STATUS_CLOSED;
                closedVacancyList.add(vacancy);
            } else {
                vacancy.Status__c = RecruitmentConstants.VACANCY_STATUS_CENCELLED;
                cancelledVacancyList.add(vacancy);
            }
        }
    }

    public static void trySetVacancyCancelledStatus (List<Vacancy__c> sourceVacancyList, List<Vacancy__c> cancelledVacancyList) {
        for (Vacancy__c vacancy : sourceVacancyList) {
            if (!isOpened(vacancy)) {
                continue;
            }

            vacancy.Status__c = RecruitmentConstants.VACANCY_STATUS_CENCELLED;
            cancelledVacancyList.add(vacancy);
        }
    }

    public static boolean isOpened(Vacancy__c vacancy) {
        return vacancy.Status__c != RecruitmentConstants.VACANCY_STATUS_CENCELLED
            && vacancy.Status__c != RecruitmentConstants.VACANCY_STATUS_CLOSED;
    }

    public static boolean isCancelled(Vacancy__c vacancy) {
        return (vacancy.Candidate__c == null || String.IsEmpty(vacancy.Candidate__c)) && vacancy.Status__c == RecruitmentConstants.VACANCY_STATUS_CENCELLED;
    }

    public static boolean isClosed(Vacancy__c vacancy) {
        return vacancy.Candidate__c != null && !String.IsEmpty(vacancy.Candidate__c) && vacancy.Status__c == RecruitmentConstants.VACANCY_STATUS_CLOSED;
    }

    public static boolean canBeClosed(Vacancy__c vacancy) {
        return isOpened(vacancy) && vacancy.Candidate__c != null && !String.IsEmpty(vacancy.Candidate__c);
    }
}