force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated by HR</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vacancy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Recruiter who accepted this vacancy and is responsible for search (Only Recruiter role can be assigned)</description>
    <label>Responsible</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only Recruiter role can be assigned</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Recruiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Vacancies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Vacancy status, &quot;New&quot; and &quot;In-Process&quot; are set by the system. &quot;Cancelled&quot; and &quot;Closed&quot; are available only when the vacancy is already saved and can be edited only by the Manager who opened the vacancy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/VacancyCandidateAssociation__c.object-meta.xml
<CustomObject>
    <label>Candidate to Vacancy</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>VacancyCandidateAssociation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates to Vacancy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR 2</booleanFilter>
        <errorMessage>Please associate only candidates that are under your ownership and are Validated by HR.</errorMessage>
        <filterItems>
            <field>Candidate__c.OwnerId</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>Candidate__c.Status__c</field>
            <operation>equals</operation>
            <value>Validated by HR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Assign Vacancy</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/VacancyCandidateAssociation__c/fields/Vacancy__c.field-meta.xml
<CustomField>
    <fullName>Vacancy__c</fullName>
    <label>Vacancy</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Vacancy is not In-Process or you are not responsible for this vacancy.</errorMessage>
        <filterItems>
            <field>Vacancy__c.Status__c</field>
            <operation>equals</operation>
            <value>In-Process</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Vacancy__c.Responsible__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Assign Candidate</relationshipLabel>
    <relationshipName>VacancyCandidateAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/TestManageVacanciesExt.cls
@IsTest
public class TestManageVacanciesExt{

    @TestSetup static void setup() {
        // Create common user accounts 
        Profile mp = [SELECT Id FROM Profile WHERE Name='Manager'];
        System.debug('Manager Profile: ' + mp.Id);
        User manager = new User(Alias = 'muser', Email='muser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles', Username='muser@testorg.com');
        manager.ProfileId = mp.Id;
        insert manager;

        Profile rp = [SELECT Id FROM Profile WHERE Name='Recruiter'];
        System.debug('Recruiter Profile: ' + rp.Id);
        User recruiter = new User(Alias = 'ruser', Email='ruser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles', Username='ruser@testorg.com');
        recruiter.ProfileId = rp.Id;
        insert recruiter;

        System.runAs(recruiter) {
            Candidate__c candidate = new Candidate__c(Status__c = 'Validated By HR');
            insert candidate;
        }
    }

    private static testMethod void TestMyVacanciesExtNoVacancies(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Vacancy__c vacancy;
        System.runAs(manager) {
            List <Vacancy__c> lstVacancy = new List<Vacancy__c>();

            insert  lstVacancy;
 
            // Act
            Test.startTest();
            Test.setCurrentPage(Page.ManageVacancies);
            ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(lstVacancy);
            stdSetController.setSelected(lstVacancy);
            ManageVacanciesExt ext = new ManageVacanciesExt(stdSetController);

            ext.onload();
            ext.getSelected();

            Test.stopTest();
        }
    }

    private static testMethod void TestMyVacanciesExtHaveVacancy(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Vacancy__c vacancy;
        System.runAs(manager) {
            List <Vacancy__c> lstVacancy = new List<Vacancy__c>();
 
            Vacancy__c testVacancy = new Vacancy__c(Responsible__c=recruiter.Id);
            lstVacancy.add(testVacancy);
            Vacancy__c testVacancy1 = new Vacancy__c(Responsible__c=recruiter.Id);
            lstVacancy.add(testVacancy1);

            insert  lstVacancy;
 
            // Act
            Test.startTest();
            Test.setCurrentPage(Page.ManageVacancies);
            ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(lstVacancy);
            stdSetController.setSelected(lstVacancy);
            ManageVacanciesExt ext = new ManageVacanciesExt(stdSetController);

            ext.onload();
            ext.getSelected();

            Test.stopTest();
        }
    }

    private static testMethod void TestMyVacanciesExtHaveVacancySelected(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Vacancy__c vacancy;
        System.runAs(manager) {
            List <Vacancy__c> lstVacancy = new List<Vacancy__c>();
 
            Vacancy__c testVacancy = new Vacancy__c(Responsible__c=recruiter.Id);
            lstVacancy.add(testVacancy);
            Vacancy__c testVacancy1 = new Vacancy__c(Responsible__c=recruiter.Id);
            lstVacancy.add(testVacancy1);

            insert  lstVacancy;
 
            // Act
            Test.startTest();
            Test.setCurrentPage(Page.ManageVacancies);
            ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(lstVacancy);
            stdSetController.setSelected(lstVacancy);
            ManageVacanciesExt ext = new ManageVacanciesExt(stdSetController);

            
            ext.onload();
            ext.vacList[0].selected = true;
            ext.getSelected();

            Test.stopTest();
        }
    }

    private static testMethod void TestMyVacanciesExtHaveVacancySelectedAndCancelled(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Vacancy__c vacancy;
        System.runAs(manager) {
            List <Vacancy__c> lstVacancy = new List<Vacancy__c>();
 
            Vacancy__c testVacancy = new Vacancy__c(Responsible__c=recruiter.Id);
            lstVacancy.add(testVacancy);
            Vacancy__c testVacancy1 = new Vacancy__c(Responsible__c=recruiter.Id);
            lstVacancy.add(testVacancy1);

            insert  lstVacancy;
 
            // Act
            Test.startTest();
            Test.setCurrentPage(Page.ManageVacancies);
            ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(lstVacancy);
            stdSetController.setSelected(lstVacancy);
            ManageVacanciesExt ext = new ManageVacanciesExt(stdSetController);

            
            ext.onload();
            ext.vacList[0].selected = true;
            ext.getSelected();
            Map<Id, List<Candidate__c>> vacancyCandidateDetails = ext.vacancyCandidateDetailsMap;
            ext.cancelVacancies();

            Test.stopTest();
        }
    }

    private static testMethod void TestMyVacanciesExtHaveVacancyAndCandidatesSelectedAndClosed(){
		// Arrange
        User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
        User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
        Vacancy__c vacancy;
        Candidate__c candidate;
        



        System.runAs(manager) {
            List <Vacancy__c> lstVacancy = new List<Vacancy__c>();
 
            Vacancy__c testVacancy = new Vacancy__c(Responsible__c=recruiter.Id);
            lstVacancy.add(testVacancy);
            Vacancy__c testVacancy1 = new Vacancy__c(Responsible__c=recruiter.Id);
            lstVacancy.add(testVacancy1);
            insert  lstVacancy;

            

            System.runAs(recruiter) {
                candidate = [SELECT Status__c FROM Candidate__c WHERE OwnerId=:recruiter.Id LIMIT 1];
                vacancy = [SELECT Status__c FROM Vacancy__c LIMIT 1];
                VacancyCandidateAssociation__c vca = new VacancyCandidateAssociation__c(Vacancy__c=vacancy.Id, Candidate__c=candidate.Id);
                insert vca;
            }
 
            // Act
            Test.startTest();
            Test.setCurrentPage(Page.ManageVacancies);
            ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(lstVacancy);
            stdSetController.setSelected(lstVacancy);
            ManageVacanciesExt ext = new ManageVacanciesExt(stdSetController);

            
            ext.onload();
            ext.vacList[0].selected = true;
            Map<Id, List<Candidate__c>> vacancyCandidateDetails = ext.vacancyCandidateDetailsMap;
            ext.vacList[0].vacancy.Candidate__c = candidate.Id;
            ext.getSelected();

            ext.closeVacancies();

            Test.stopTest();
        }
    }

    // private static testMethod void TestMyVacanciesExtHaveVacancyAndCandidatesDuplicatesSelectedAndClosed(){
	// 	// Arrange
    //     User manager = [SELECT Id FROM User WHERE Alias='muser' LIMIT 1];
    //     User recruiter = [SELECT Id FROM User WHERE Alias='ruser' LIMIT 1];
    //     Vacancy__c vacancy;
    //     Candidate__c candidate;

    //     System.runAs(manager) {
    //         List <Vacancy__c> lstVacancy = new List<Vacancy__c>();
 
    //         Vacancy__c testVacancy = new Vacancy__c(Responsible__c=recruiter.Id);
    //         lstVacancy.add(testVacancy);
    //         Vacancy__c testVacancy1 = new Vacancy__c(Responsible__c=recruiter.Id);
    //         lstVacancy.add(testVacancy1);
    //         insert  lstVacancy;

            

    //         System.runAs(recruiter) {
    //             candidate = [SELECT Status__c FROM Candidate__c WHERE OwnerId=:recruiter.Id LIMIT 1];
    //             List<VacancyCandidateAssociation__c> vcas = new List<VacancyCandidateAssociation__c>();
    //             for (Vacancy__c v : lstVacancy) {
    //                 vcas.add(new VacancyCandidateAssociation__c(Vacancy__c=v.Id, Candidate__c=candidate.Id));
    //             }
    //             insert vcas;
    //         }
 
    //         // Act
    //         Test.startTest();
    //         Test.setCurrentPage(Page.ManageVacancies);
    //         ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(lstVacancy);
    //         stdSetController.setSelected(lstVacancy);
    //         ManageVacanciesExt ext = new ManageVacanciesExt(stdSetController);

            
    //         ext.onload();
    //         ext.vacList[0].selected = true;
    //         ext.vacList[0].vacancy.Candidate__c = candidate.Id;

    //         ext.vacList[1].selected = true;
    //         ext.vacList[1].vacancy.Candidate__c = candidate.Id;
    //         ext.getSelected();

    //         ext.closeVacancies();

    //         Test.stopTest();
    //     }
    // }
}