force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated by HR</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CandidateTool.cls
public with sharing class CandidateTool {
    public static void setCandidateHired (List<Candidate__c> updateCandidateList, List<Candidate__c> hiredCandidateList) {
        System.System.debug(updateCandidateList);
        
        for (Candidate__c candidate : updateCandidateList) {
            if (!isOpened(candidate)) {
                continue;
            }

            candidate.Status__c = RecruitmentConstants.CANDIDATE_STATUS_HIRED;
            hiredCandidateList.add(candidate);
        }
    }

    public static boolean isOpened(Candidate__c candidate) {
        return candidate.Status__c != RecruitmentConstants.CANDIDATE_STATUS_DISCUALIFIED
            && candidate.Status__c != RecruitmentConstants.CANDIDATE_STATUS_HIRED;
    }
}